# Setup
title: Then go talk to a wall
tagline: I just want you to listen
lang: "ja-JP"
baseurl: ""
paginate: 1

# About/contact
author:
  name: yo1000 | YO!CHI KIKUCHI
  url: https://github.com/yo1000

permalink: none
