# Setup
title: Then go talk to a wall
tagline: The walls are listening to everything
baseurl: ""
paginate: 1
locale: "ja"

# theme: jekyll-theme-cayman

# About/contact
author:
  name: yo1000 | YO!CHI KIKUCHI
  url: http://blog.yo1000.com
